# Generated by Django 4.2.4 on 2023-08-12 16:49

from django.db import migrations

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", account.models.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="phone_Number",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="city",
        ),
        migrations.DeleteModel(
            name="City",
        ),
    ]
