# Generated by Django 4.2.4 on 2023-08-12 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="directory",
            old_name="owner",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="owner",
            new_name="user",
        ),
    ]
